-- MySQL Script generated by MySQL Workbench
-- 09/04/15 18:32:42
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema refaccion
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema refaccion
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `refaccion` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema refaccion
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema refaccion
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `refaccion` DEFAULT CHARACTER SET utf8 ;
USE `refaccion` ;

-- -----------------------------------------------------
-- Table `refaccion`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `refaccion`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `refaccion`.`Usuario` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Nombre` VARCHAR(45) NOT NULL COMMENT '',
  `Domicilio` VARCHAR(250) NOT NULL DEFAULT 'Desconocido' COMMENT '',
  `Mail` VARCHAR(150) NOT NULL COMMENT '',
  `clave` VARCHAR(45) NOT NULL COMMENT '',
  `Tel` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `Avatar` VARCHAR(145) NOT NULL COMMENT '',
  `Status` CHAR NOT NULL DEFAULT 'A' COMMENT '',
  `Estado` VARCHAR(45) NULL COMMENT '',
  `Municipio` VARCHAR(45) NULL COMMENT '',
  `password` VARCHAR(145) NOT NULL COMMENT '',
  `remember_token` VARCHAR(45) NULL COMMENT '',
  `updated_at` TIMESTAMP NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `refaccion`.`Marca`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `refaccion`.`Marca` ;

CREATE TABLE IF NOT EXISTS `refaccion`.`Marca` (
  `idMarca` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Nombre` VARCHAR(45) NOT NULL COMMENT '',
  `Descripcion` TEXT NOT NULL COMMENT '',
  `Img` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`idMarca`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `refaccion`.`Refaccion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `refaccion`.`Refaccion` ;

CREATE TABLE IF NOT EXISTS `refaccion`.`Refaccion` (
  `idRefaccion` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Nombre` VARCHAR(150) NOT NULL COMMENT '',
  `Descripcion` TEXT NOT NULL COMMENT '',
  `Tipo` VARCHAR(45) NOT NULL COMMENT '',
  `Marca` INT NOT NULL COMMENT '',
  `Status` TINYINT(1) NOT NULL COMMENT '',
  `Modelo` VARCHAR(145) NOT NULL COMMENT '',
  PRIMARY KEY (`idRefaccion`)  COMMENT '',
  INDEX `fk_Refaccion_Marca1_idx` (`Marca` ASC)  COMMENT '',
  CONSTRAINT `fk_Refaccion_Marca1`
    FOREIGN KEY (`Marca`)
    REFERENCES `refaccion`.`Marca` (`idMarca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `refaccion`.`Categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `refaccion`.`Categoria` ;

CREATE TABLE IF NOT EXISTS `refaccion`.`Categoria` (
  `idCategoria` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Nombre` VARCHAR(45) NOT NULL COMMENT '',
  `Descripcion` TEXT NOT NULL COMMENT '',
  `Status` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '',
  `Img` VARCHAR(145) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`idCategoria`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `refaccion`.`Publicacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `refaccion`.`Publicacion` ;

CREATE TABLE IF NOT EXISTS `refaccion`.`Publicacion` (
  `idPublicacion` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Fecha` DATE NOT NULL COMMENT '',
  `Status` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '',
  `Refaccion` INT NOT NULL COMMENT '',
  `Usuario` INT NOT NULL COMMENT '',
  `Categoria` INT NOT NULL COMMENT '',
  `Departamento` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`idPublicacion`)  COMMENT '',
  INDEX `fk_Publicacion_Refaccion1_idx` (`Refaccion` ASC)  COMMENT '',
  INDEX `fk_Publicacion_Usuario1_idx` (`Usuario` ASC)  COMMENT '',
  INDEX `fk_Publicacion_Categoria1_idx` (`Categoria` ASC)  COMMENT '',
  CONSTRAINT `fk_Publicacion_Refaccion1`
    FOREIGN KEY (`Refaccion`)
    REFERENCES `refaccion`.`Refaccion` (`idRefaccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Publicacion_Usuario1`
    FOREIGN KEY (`Usuario`)
    REFERENCES `refaccion`.`Usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Publicacion_Categoria1`
    FOREIGN KEY (`Categoria`)
    REFERENCES `refaccion`.`Categoria` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `refaccion`.`Notificaciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `refaccion`.`Notificaciones` ;

CREATE TABLE IF NOT EXISTS `refaccion`.`Notificaciones` (
  `idNotificaciones` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Contenido` VARCHAR(245) NOT NULL COMMENT '',
  `Status` TINYINT(1) NOT NULL COMMENT '',
  `Fecha` DATE NOT NULL COMMENT '',
  `Url` VARCHAR(145) NOT NULL COMMENT '',
  `Usuario` INT NOT NULL COMMENT '',
  `Publicacion` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idNotificaciones`)  COMMENT '',
  INDEX `fk_Notificaciones_Usuario_idx` (`Usuario` ASC)  COMMENT '',
  INDEX `fk_Notificaciones_Publicacion1_idx` (`Publicacion` ASC)  COMMENT '',
  CONSTRAINT `fk_Notificaciones_Usuario`
    FOREIGN KEY (`Usuario`)
    REFERENCES `refaccion`.`Usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Notificaciones_Publicacion1`
    FOREIGN KEY (`Publicacion`)
    REFERENCES `refaccion`.`Publicacion` (`idPublicacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `refaccion`.`Vendedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `refaccion`.`Vendedor` ;

CREATE TABLE IF NOT EXISTS `refaccion`.`Vendedor` (
  `idVendedor` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Usuario` INT NOT NULL COMMENT '',
  `Status` CHAR NOT NULL DEFAULT 'A' COMMENT '',
  `Privada` VARCHAR(100) NULL COMMENT '',
  `Publica` VARCHAR(100) NULL COMMENT '',
  PRIMARY KEY (`idVendedor`)  COMMENT '',
  INDEX `fk_Vendedor_Usuario_idx` (`Usuario` ASC)  COMMENT '',
  CONSTRAINT `fk_Vendedor_Usuario`
    FOREIGN KEY (`Usuario`)
    REFERENCES `refaccion`.`Usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `refaccion`.`keywords`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `refaccion`.`keywords` ;

CREATE TABLE IF NOT EXISTS `refaccion`.`keywords` (
  `idKeywords` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Meta` VARCHAR(145) NOT NULL COMMENT '',
  `Status` TINYINT(1) NOT NULL COMMENT '',
  `Vendedor` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idKeywords`)  COMMENT '',
  INDEX `fk_keywords_Vendedor1_idx` (`Vendedor` ASC)  COMMENT '',
  CONSTRAINT `fk_keywords_Vendedor1`
    FOREIGN KEY (`Vendedor`)
    REFERENCES `refaccion`.`Vendedor` (`idVendedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `refaccion` ;

-- -----------------------------------------------------
-- Table `refaccion`.`Marca_Categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `refaccion`.`Marca_Categoria` ;

CREATE TABLE IF NOT EXISTS `refaccion`.`Marca_Categoria` (
  `Marca` INT NOT NULL COMMENT '',
  `Categoria` INT NOT NULL COMMENT '',
  `Status` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '',
  PRIMARY KEY (`Marca`, `Categoria`)  COMMENT '',
  INDEX `fk_Marca_has_Categoria_Categoria1_idx` (`Categoria` ASC)  COMMENT '',
  INDEX `fk_Marca_has_Categoria_Marca1_idx` (`Marca` ASC)  COMMENT '',
  CONSTRAINT `fk_Marca_has_Categoria_Marca1`
    FOREIGN KEY (`Marca`)
    REFERENCES `refaccion`.`Marca` (`idMarca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Marca_has_Categoria_Categoria1`
    FOREIGN KEY (`Categoria`)
    REFERENCES `refaccion`.`Categoria` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `refaccion`.`Suscripciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `refaccion`.`Suscripciones` ;

CREATE TABLE IF NOT EXISTS `refaccion`.`Suscripciones` (
  `Vendedor` INT NOT NULL COMMENT '',
  `Marca` INT NOT NULL COMMENT '',
  `Categoria` INT NOT NULL COMMENT '',
  `Suscripciones` INT NOT NULL COMMENT '',
  INDEX `fk_Suscripciones_Vendedor1_idx` (`Vendedor` ASC)  COMMENT '',
  PRIMARY KEY (`Vendedor`, `Marca`, `Categoria`)  COMMENT '',
  INDEX `fk_Suscripciones_Marca1_idx` (`Marca` ASC)  COMMENT '',
  INDEX `fk_Suscripciones_Categoria1_idx` (`Categoria` ASC)  COMMENT '',
  CONSTRAINT `fk_Suscripciones_Vendedor1`
    FOREIGN KEY (`Vendedor`)
    REFERENCES `refaccion`.`Vendedor` (`idVendedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Suscripciones_Marca1`
    FOREIGN KEY (`Marca`)
    REFERENCES `refaccion`.`Marca` (`idMarca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Suscripciones_Categoria1`
    FOREIGN KEY (`Categoria`)
    REFERENCES `refaccion`.`Categoria` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `refaccion`.`Oferta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `refaccion`.`Oferta` ;

CREATE TABLE IF NOT EXISTS `refaccion`.`Oferta` (
  `idOferta` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Precio` DECIMAL(10,2) NOT NULL COMMENT '',
  `Publicacion` INT NOT NULL COMMENT '',
  `Vendedor` INT NOT NULL COMMENT '',
  `Estado` CHAR NOT NULL DEFAULT 'A' COMMENT '',
  `TiempoE` VARCHAR(145) NOT NULL COMMENT '',
  `Status` VARCHAR(45) NULL COMMENT '',
  `Refaccion` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idOferta`)  COMMENT '',
  INDEX `fk_Oferta_Publicacion1_idx` (`Publicacion` ASC)  COMMENT '',
  INDEX `fk_Oferta_Vendedor1_idx` (`Vendedor` ASC)  COMMENT '',
  INDEX `fk_Oferta_Refaccion1_idx` (`Refaccion` ASC)  COMMENT '',
  CONSTRAINT `fk_Oferta_Publicacion1`
    FOREIGN KEY (`Publicacion`)
    REFERENCES `refaccion`.`Publicacion` (`idPublicacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Oferta_Vendedor1`
    FOREIGN KEY (`Vendedor`)
    REFERENCES `refaccion`.`Vendedor` (`idVendedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Oferta_Refaccion1`
    FOREIGN KEY (`Refaccion`)
    REFERENCES `refaccion`.`Refaccion` (`idRefaccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `refaccion`.`Pasarela`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `refaccion`.`Pasarela` ;

CREATE TABLE IF NOT EXISTS `refaccion`.`Pasarela` (
  `idPasarela` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `PrivateKey` VARCHAR(50) NOT NULL COMMENT '',
  `PublicKey` VARCHAR(50) NOT NULL COMMENT '',
  `Vendedor` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idPasarela`, `Vendedor`)  COMMENT '',
  INDEX `fk_Pasarela_Vendedor1_idx` (`Vendedor` ASC)  COMMENT '',
  CONSTRAINT `fk_Pasarela_Vendedor1`
    FOREIGN KEY (`Vendedor`)
    REFERENCES `refaccion`.`Vendedor` (`idVendedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `refaccion`.`Reputacion_Vendedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `refaccion`.`Reputacion_Vendedor` ;

CREATE TABLE IF NOT EXISTS `refaccion`.`Reputacion_Vendedor` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Usuario` INT NOT NULL COMMENT '',
  `Vendedor` INT NOT NULL COMMENT '',
  `Calificacion` INT NOT NULL COMMENT '',
  `Comentario` TEXT NULL DEFAULT NULL COMMENT '',
  INDEX `fk_Usuario_has_Vendedor_Vendedor1_idx` (`Vendedor` ASC)  COMMENT '',
  INDEX `fk_Usuario_has_Vendedor_Usuario1_idx` (`Usuario` ASC)  COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  CONSTRAINT `fk_Usuario_has_Vendedor_Usuario1`
    FOREIGN KEY (`Usuario`)
    REFERENCES `refaccion`.`Usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_has_Vendedor_Vendedor1`
    FOREIGN KEY (`Vendedor`)
    REFERENCES `refaccion`.`Vendedor` (`idVendedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `refaccion`.`Reputacion_Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `refaccion`.`Reputacion_Usuario` ;

CREATE TABLE IF NOT EXISTS `refaccion`.`Reputacion_Usuario` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Vendedor` INT NOT NULL COMMENT '',
  `Usuario` INT NOT NULL COMMENT '',
  `Calificacion` INT NOT NULL COMMENT '',
  `Comentario` TEXT NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_Vendedor_has_Usuario_Usuario1_idx` (`Usuario` ASC)  COMMENT '',
  INDEX `fk_Vendedor_has_Usuario_Vendedor1_idx` (`Vendedor` ASC)  COMMENT '',
  CONSTRAINT `fk_Vendedor_has_Usuario_Vendedor1`
    FOREIGN KEY (`Vendedor`)
    REFERENCES `refaccion`.`Vendedor` (`idVendedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vendedor_has_Usuario_Usuario1`
    FOREIGN KEY (`Usuario`)
    REFERENCES `refaccion`.`Usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `refaccion`.`Comentarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `refaccion`.`Comentarios` ;

CREATE TABLE IF NOT EXISTS `refaccion`.`Comentarios` (
  `idComentarios` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `date` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `Comentario` TEXT NULL DEFAULT NULL COMMENT '',
  `Oferta` INT NOT NULL COMMENT '',
  `Usuario` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idComentarios`)  COMMENT '',
  INDEX `fk_Comentarios_Oferta1_idx` (`Oferta` ASC)  COMMENT '',
  INDEX `fk_Comentarios_Usuario1_idx` (`Usuario` ASC)  COMMENT '',
  CONSTRAINT `fk_Comentarios_Oferta1`
    FOREIGN KEY (`Oferta`)
    REFERENCES `refaccion`.`Oferta` (`idOferta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comentarios_Usuario1`
    FOREIGN KEY (`Usuario`)
    REFERENCES `refaccion`.`Usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `refaccion`.`Galeria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `refaccion`.`Galeria` ;

CREATE TABLE IF NOT EXISTS `refaccion`.`Galeria` (
  `idGaleria` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Nombre` VARCHAR(145) NOT NULL COMMENT '',
  `Archivo` VARCHAR(145) NOT NULL COMMENT '',
  `Status` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '',
  `Refaccion` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idGaleria`)  COMMENT '',
  INDEX `fk_Galeria_Refaccion1_idx` (`Refaccion` ASC)  COMMENT '',
  CONSTRAINT `fk_Galeria_Refaccion1`
    FOREIGN KEY (`Refaccion`)
    REFERENCES `refaccion`.`Refaccion` (`idRefaccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `refaccion`.`Compra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `refaccion`.`Compra` ;

CREATE TABLE IF NOT EXISTS `refaccion`.`Compra` (
  `idCompra` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Fecha` DATE NOT NULL COMMENT '',
  `Forma` VARCHAR(145) NOT NULL COMMENT '',
  `Status` CHAR NOT NULL DEFAULT 'A' COMMENT '',
  `Oferta` INT NOT NULL COMMENT '',
  `Publicacion` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idCompra`)  COMMENT '',
  INDEX `fk_Compra_Oferta1_idx` (`Oferta` ASC)  COMMENT '',
  INDEX `fk_Compra_Publicacion1_idx` (`Publicacion` ASC)  COMMENT '',
  CONSTRAINT `fk_Compra_Oferta1`
    FOREIGN KEY (`Oferta`)
    REFERENCES `refaccion`.`Oferta` (`idOferta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Compra_Publicacion1`
    FOREIGN KEY (`Publicacion`)
    REFERENCES `refaccion`.`Publicacion` (`idPublicacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `refaccion`.`Trato`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `refaccion`.`Trato` ;

CREATE TABLE IF NOT EXISTS `refaccion`.`Trato` (
  `Publicacion` INT NOT NULL COMMENT '',
  `Vendedor` INT NOT NULL COMMENT '',
  `Fecha` DATE NOT NULL COMMENT '',
  `Status` TINYINT(1) NOT NULL COMMENT '',
  INDEX `fk_Trato_Publicacion1_idx` (`Publicacion` ASC)  COMMENT '',
  INDEX `fk_Trato_Vendedor1_idx` (`Vendedor` ASC)  COMMENT '',
  PRIMARY KEY (`Publicacion`, `Vendedor`)  COMMENT '',
  CONSTRAINT `fk_Trato_Publicacion1`
    FOREIGN KEY (`Publicacion`)
    REFERENCES `refaccion`.`Publicacion` (`idPublicacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Trato_Vendedor1`
    FOREIGN KEY (`Vendedor`)
    REFERENCES `refaccion`.`Vendedor` (`idVendedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `refaccion`.`Ticket`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `refaccion`.`Ticket` ;

CREATE TABLE IF NOT EXISTS `refaccion`.`Ticket` (
  `idTicket` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Asunto` VARCHAR(145) NOT NULL COMMENT '',
  `Fecha` DATE NOT NULL COMMENT '',
  `Status` CHAR NOT NULL COMMENT '',
  `Usuario` INT NOT NULL COMMENT '',
  `Departamento` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`idTicket`)  COMMENT '',
  INDEX `fk_Ticket_Usuario1_idx` (`Usuario` ASC)  COMMENT '',
  CONSTRAINT `fk_Ticket_Usuario1`
    FOREIGN KEY (`Usuario`)
    REFERENCES `refaccion`.`Usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `refaccion`.`Pregunta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `refaccion`.`Pregunta` ;

CREATE TABLE IF NOT EXISTS `refaccion`.`Pregunta` (
  `idPregunta` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Fecha` DATE NOT NULL COMMENT '',
  `Contenido` TEXT NOT NULL COMMENT '',
  `Status` CHAR NOT NULL COMMENT '',
  `Ticket` INT NOT NULL COMMENT '',
  `Usuario` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idPregunta`)  COMMENT '',
  INDEX `fk_Pregunta_Ticket1_idx` (`Ticket` ASC)  COMMENT '',
  INDEX `fk_Pregunta_Usuario1_idx` (`Usuario` ASC)  COMMENT '',
  CONSTRAINT `fk_Pregunta_Ticket1`
    FOREIGN KEY (`Ticket`)
    REFERENCES `refaccion`.`Ticket` (`idTicket`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pregunta_Usuario1`
    FOREIGN KEY (`Usuario`)
    REFERENCES `refaccion`.`Usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
